version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-opt.txt
    - requirements: requirements-doc.txt
    - method: pip
      path: .

sphinx:
  configuration: doc/source/conf.py
